"""
===============================================================================
  Exonik - Módulo de enfermedad: Anemia Falciforme (Sickle Cell Anemia, SCA)
===============================================================================

CASO BASE de Exonik. Los valores aquí son EXACTAMENTE los que estaban cableados
en config.py, extraídos sin modificación para garantizar que el pipeline
produzca resultados idénticos a los ya validados (Fases 0-6).

  - Gen:       HBB (Hemoglobina Beta), cromosoma 11
  - Mutación:  c.20A>T (GAG → GTG en codón 7) → Glu → Val (E7V) → HbS
  - Herencia:  Autosómica recesiva
  - dbSNP:     rs334
"""

from .base import Disease

# CDS completa del gen HBB normal (NM_000518.5) - 444 nucleótidos
_HBB_CDS_NORMAL = (
    "ATGGTGCACCTGACTCCTGAGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAGGTG"
    "AACGTGGATGAAGTTGGTGGTGAGGCCCTGGGCAGGCTGCTGGTGGTCTACCCTTG"
    "GACCCAGAGGTTCTTTGAGTCCTTTGGGGATCTGTCCACTCCTGATGCTGTTATGGG"
    "CAACCCTAAGGTGAAGGCTCATGGCAAGAAAGTGCTCGGTGCCTTTAGTGATGGCCT"
    "GGCTCACCTGGACAACCTCAAGGGCACCTTTGCTCACTGCAGTGAATTCTCACTGGA"
    "CAAAGCCTTTGAGGAACTGATGATGTGCTCGATGCCAGCCCATCACTTTGGCAAAGA"
    "ATTCACCCCACCAGTGCAGGCTGCCTATCAGAAAGTGGTGGCTGGTGTGGCTAATGC"
    "CCTGGCCCACAAGTATCACTAA"
)

# CDS del gen HBB con mutación SCA (c.20A>T)
_HBB_CDS_SCA = (
    "ATGGTGCACCTGACTCCTGTGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAGGTG"
    "AACGTGGATGAAGTTGGTGGTGAGGCCCTGGGCAGGCTGCTGGTGGTCTACCCTTG"
    "GACCCAGAGGTTCTTTGAGTCCTTTGGGGATCTGTCCACTCCTGATGCTGTTATGGG"
    "CAACCCTAAGGTGAAGGCTCATGGCAAGAAAGTGCTCGGTGCCTTTAGTGATGGCCT"
    "GGCTCACCTGGACAACCTCAAGGGCACCTTTGCTCACTGCAGTGAATTCTCACTGGA"
    "CAAAGCCTTTGAGGAACTGATGATGTGCTCGATGCCAGCCCATCACTTTGGCAAAGA"
    "ATTCACCCCACCAGTGCAGGCTGCCTATCAGAAAGTGGTGGCTGGTGTGGCTAATGC"
    "CCTGGCCCACAAGTATCACTAA"
)

_HBB_REGION_GENOMICA = (
    "TAAACTGCAGGCATGCAAGCTTGGCGTAATCATGGTCATAGCTGTTTCCTGTGTGAAATTGT"
    "TATCCGCTCACAATTCCACACAACATACGAGCCGGAAGCATAAAGTGTAAAGCCTGGGGTGC"
    "CTAATGAGTGAGCTAACTCACATTAATTGCGTTGCGCTCACTGCCCGCTTTCCAGTCGGGA"
    "AACCTGTCGTGCCAGCTGCATTAATGAATCGGCCAACGCGCGGGGAGAGGCGGTTTGCGTA"
    "TTGGGCGCTCTTCCGCTTCCTCGCTCACTGACTCGCTGCGCTCGGTCGTTCGGCTGCGGCG"
    "ACATTTGCTTCTGACACAACTGTGTTCACTAGCAACCTCAAACAGACACCATGGTGCACCTG"
    "ACTCCTGAGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAGGTGAACGTGGATGAAGTTG"
    "GTGGTGAGGCCCTGGGCAGGCTGCTGGTGGTCTACCCTTGGACCCAGAGGTTCTTTGAGTC"
    "CTTTGGGGATCTGTCCACTCCTGATGCTGTTATGGGCAACCCTAAGGTGAAGGCTCATGGCA"
    "AGAAAGTGCTCGGTGCCTTTAGTGATGGCCTGGCTCACCTGGACAACCTCAAGGGCACCTTT"
)

_HBB_PROTEINA_NORMAL = (
    "MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKV"
    "LGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVA"
    "GVANALAHKYH"
)

_HBB_PROTEINA_SCA = (
    "MVHLTPVEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKV"
    "LGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVA"
    "GVANALAHKYH"
)

_BCL11A_REGION_ENHANCER = (
    "CTAACAGTTGCTTTTATCACAGGCTCCAGGAAGGGTTTGGCCTCTGATTAGGGTGCAGCGATG"
    "CACTCATGATGGCACTGACTCTTTCAAGGGTCCTGAGTCCAGCAGTGTGAATCACTGTGTAA"
    "GCAGGATCCAGGGCGACTGTTTCTAGAGATAATCTGATAATTTGTGATTATGATGTAATCAGG"
    "CATCTCAGCAAAGACTAAACCTGCAATTGATGGCCCTGTCATTTCATCTGCAATACCTTGGCT"
    "TCTTGAAGACAGGGGCCAGTGTCCACTCCTGGTACCAGGATCCCTTTCCTGAAGGGATTTACT"
)


DISEASE = Disease(
    key="sca",
    nombre="Anemia Falciforme (Sickle Cell Anemia)",
    gene="HBB",
    cromosoma="chr11",
    herencia="Autosómica recesiva",
    estrategia="correccion",

    cds_normal=_HBB_CDS_NORMAL,
    cds_mutante=_HBB_CDS_SCA,
    proteina_normal=_HBB_PROTEINA_NORMAL,
    proteina_mutante=_HBB_PROTEINA_SCA,

    variante_pos_cds=19,          # 0-indexed (nucleótido 20, c.20A>T)
    variante_ref="A",
    variante_alt="T",
    variante_rs_id="rs334",
    codon_normal="GAG",           # Glutámico (Glu, E)
    codon_mutante="GTG",          # Valina (Val, V)

    region_genomica=_HBB_REGION_GENOMICA,
    atg_offset=339,
    pos_genomica_mutacion=5227002,

    # Estrategia alternativa: disrupción del enhancer eritroide de BCL11A (HbF)
    alt_nombre="BCL11A",
    alt_region=_BCL11A_REGION_ENHANCER,
    alt_cromosoma="chr2",
    alt_pos_inicio=60716189,
    alt_pos_fin=60728612,
    alt_guide_prefix="BCL",       # conserva los IDs de guía ya validados (BCL-gNN)

    prevalencia="~20-25 millones con SCA; ~300 millones portadores",
    terapia_aprobada="Casgevy / Lyfgenia (2023) — CRISPR, ~$2.2M por paciente",
    uniprot_id="P68871",          # HBB humana
    poblaciones_interes=("ACB", "ESN", "GWD", "CLM", "PUR"),

    # Etiquetas de presentacion (textos originales, para reporte identico)
    proteina_nombre="Hemoglobina Beta (HBB) normal",
    proteina_funcion="Transporte de oxigeno en eritrocitos",
    terapia_objetivo="Reemplazar HbS defectuosa por HbA funcional",
    tejido_objetivo="Precursores eritroides (medula osea)",
    targeting="Anti-CD71 (receptor de transferrina)",
    nota_inmunogenicidad="HBB es proteina endogena -> riesgo inmune minimo",
)
